plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
}

android {
    namespace 'com.example.notificationwebhookapp'
    compileSdk 36

    defaultConfig {
        applicationId "com.example.notificationwebhookapp"
        minSdk 31
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        compose true
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11
    }
}

dependencies {
    implementation libs.miuix.ui
    implementation libs.compose.foundation
    implementation libs.activity.compose
    implementation libs.lifecycle.viewmodel.ktx
    implementation 'androidx.work:work-runtime:2.11.2'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20240303'
}
