plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.notificationwebhookapp'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.notificationwebhookapp"
        minSdk 31
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.work:work-runtime:2.11.2'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20240303'
}
